baseurl = "https://downloads.sajal.co/"
languageCode = "en-us"
languageLang = "en"
title = "Sajal Mondal"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
